In [ ]:
pip list

Package                       Version
----------------------------- ---------------------
absl-py                       1.0.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.2.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.11.4
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.4.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.1.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.4
branca                        0.4.2
bs4                           0.0.1
CacheC

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['sunny' 85.0 85.0]
 ['sunny' 80.0 90.0]
 ['overcast' 83.0 78.0]
 ['rain' 70.0 96.0]
 ['rain' nan 80.0]
 ['rain' 65.0 70.0]
 ['overcast' 64.0 65.0]
 ['sunny' 72.0 95.0]
 ['sunny' 69.0 nan]
 ['rain' 75.0 80.0]
 ['sunny' 75.0 70.0]
 ['overcast' 72.0 90.0]
 ['overcast' 81.0 75.0]
 ['rain' 71.0 80.0]]


In [ ]:
print(y)

['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']


In [32]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [33]:
print(x)

[['sunny' 85.0 85.0]
 ['sunny' 80.0 90.0]
 ['overcast' 83.0 78.0]
 ['rain' 70.0 96.0]
 ['rain' 74.0 80.0]
 ['rain' 65.0 70.0]
 ['overcast' 64.0 65.0]
 ['sunny' 72.0 95.0]
 ['sunny' 69.0 81.07692307692308]
 ['rain' 75.0 80.0]
 ['sunny' 75.0 70.0]
 ['overcast' 72.0 90.0]
 ['overcast' 81.0 75.0]
 ['rain' 71.0 80.0]]


In [47]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [35]:
print(x)

[[0.0 0.0 1.0 85.0 85.0]
 [0.0 0.0 1.0 80.0 90.0]
 [1.0 0.0 0.0 83.0 78.0]
 [0.0 1.0 0.0 70.0 96.0]
 [0.0 1.0 0.0 74.0 80.0]
 [0.0 1.0 0.0 65.0 70.0]
 [1.0 0.0 0.0 64.0 65.0]
 [0.0 0.0 1.0 72.0 95.0]
 [0.0 0.0 1.0 69.0 81.07692307692308]
 [0.0 1.0 0.0 75.0 80.0]
 [0.0 0.0 1.0 75.0 70.0]
 [1.0 0.0 0.0 72.0 90.0]
 [1.0 0.0 0.0 81.0 75.0]
 [0.0 1.0 0.0 71.0 80.0]]


In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [37]:
print(y)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [39]:
print(x_train)

[[1.0 0.0 0.0 83.0 78.0]
 [0.0 0.0 1.0 75.0 70.0]
 [0.0 1.0 0.0 74.0 80.0]
 [0.0 0.0 1.0 80.0 90.0]
 [1.0 0.0 0.0 81.0 75.0]
 [0.0 0.0 1.0 85.0 85.0]
 [0.0 1.0 0.0 71.0 80.0]
 [0.0 1.0 0.0 75.0 80.0]
 [0.0 0.0 1.0 69.0 81.07692307692308]
 [1.0 0.0 0.0 72.0 90.0]
 [0.0 1.0 0.0 65.0 70.0]]


In [40]:
print(x_test)

[[0.0 1.0 0.0 70.0 96.0]
 [0.0 0.0 1.0 72.0 95.0]
 [1.0 0.0 0.0 64.0 65.0]]


In [41]:
print(y_train)

[1 1 1 0 1 0 0 1 1 1 0]


In [42]:
print(y_test)

[1 0 1]


In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:,3:])

In [44]:
print(x_train)

[[1.0 0.0 0.0 1.2758665834452925 -0.29789683881853696]
 [0.0 0.0 1.0 -0.07685943273766799 -1.5416705016229366]
 [0.0 1.0 0.0 -0.24595018476053807 0.013046576882562985]
 [0.0 0.0 1.0 0.7685943273766823 1.5677636553880627]
 [1.0 0.0 0.0 0.9376850793995524 -0.7643119623701868]
 [0.0 0.0 1.0 1.6140480874910326 0.7904051161353128]
 [0.0 1.0 0.0 -0.7532224408291482 0.013046576882562985]
 [0.0 1.0 0.0 -0.07685943273766799 0.013046576882562985]
 [0.0 0.0 1.0 -1.0914039448748885 0.18047764687546347]
 [1.0 0.0 0.0 -0.5841316888062782 1.5677636553880627]
 [0.0 1.0 0.0 -1.7677669529663687 -1.5416705016229366]]


In [45]:
print(x_test)

[[0.0 1.0 0.0 -0.9223131928520183 2.5005939024913624]
 [0.0 0.0 1.0 -0.5841316888062782 2.3451221946408123]
 [1.0 0.0 0.0 -1.9368577049892386 -2.3190290408756864]]
